### ISSUE TITLE
Error getting values from post request

### ISSUE THREAD

**Issue by KyleBehiels** [KyleBehiels/python_email_challenge#3]
Attempts to process post requests are generating an error. Below is the stack trace

`Traceback (most recent call last):
  File "C:\Users\kyleb\Desktop\workspace\python_email_challenge\env\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\kyleb\Desktop\workspace\python_email_challenge\env\lib\site-packages\flask\app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\kyleb\Desktop\workspace\python_email_challenge\env\lib\site-packages\flask\app.py", line 1630, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\kyleb\Desktop\workspace\python_email_challenge\env\lib\site-packages\flask\app.py", line 1725, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
127.0.0.1 - - [07/May/2017 00:12:56] "POST /form_page HTTP/1.1" 500 -
`

Deal with it tomorrow

**Comment by KyleBehiels** [comment]
Fixed by returning the function that handles the post request
`sendCredentials(username, password)
		return render_template("simple_form.html")`
